# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - applicationcheck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerkast.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9b158dc065e64358bed7d4fc72c68585 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e4d8f40129694c7d90064fecc708ce49 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerkast.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9b158dc065e64358bed7d4fc72c68585 }}/application:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'applicationcheck'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_51bf1a0dd80044f48a33e11d57e70dd8 }}
        images: 'testdockerkast.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9b158dc065e64358bed7d4fc72c68585 }}/application:${{ github.sha }}'